# ================================
# Server
# ================================
server.port=8081

# ================================
# PostgreSQL Database
# ================================
#postgresql://ruthvik:GkGbzmXU7CyR2AijMe0vuvtlR9DNHAzK@dpg-d70g0hvdiees73dke5qg-a.oregon-postgres.render.com/expensetracker_gjf3
spring.datasource.url=jdbc:postgresql://dpg-d70g0hvdiees73dke5qg-a.oregon-postgres.render.com/expensetracker_gjf3
spring.datasource.username=ruthvik
spring.datasource.password=GkGbzmXU7CyR2AijMe0vuvtlR9DNHAzK
spring.datasource.driver-class-name=org.postgresql.Driver

# ================================
# JPA / Hibernate
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ================================
# Connection Pool
# ================================
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5